package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"gin-graphql-example/graph/model"
	"github.com/google/uuid"
)

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, title string, author string) (*model.Book, error) {
	bookUUID, err := uuid.NewUUID()
	if err != nil {
		return nil, err
	}
	book := model.Book{
		ID:          bookUUID.String(),
		Title:       title,
		Author:      author,
		IsAvailable: true,
	}

	r.Storage.PutObject(book.ID, book)

	return &book, nil
}

// BorrowBook is the resolver for the borrowBook field.
func (r *mutationResolver) BorrowBook(ctx context.Context, id string) (*model.Book, error) {
	item, ok := r.GetObject(id)
	if !ok {
		return nil, fmt.Errorf("item with id: %s not found in storage", id)
	}
	book, ok := item.(model.Book)
	if !ok {
		return nil, fmt.Errorf("item with id: %s is not a book ", id)
	}

	if !book.IsAvailable {
		return nil, fmt.Errorf("book %s is already checked out", book.Title)
	}

	book.IsAvailable = false
	r.Storage.PutObject(book.ID, book)

	return &book, nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	booksIfaces := r.Storage.GetAll()
	var books []*model.Book
	for _, b := range booksIfaces {
		if book, ok := b.(model.Book); ok {
			books = append(books, &book)
		}
	}
	if len(books) == 0 {
		return nil, fmt.Errorf("no books in the library")
	}
	return books, nil
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, id string) (*model.Book, error) {
	item, ok := r.GetObject(id)
	if !ok {
		return nil, fmt.Errorf("item with id: %s not found in storage", id)
	}

	book, ok := item.(model.Book)
	if !ok {
		return nil, fmt.Errorf("item with id: %s is not a book ", id)
	}

	return &book, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
