// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Author      string `json:"author"`
	IsAvailable bool   `json:"isAvailable"`
}

type Mutation struct {
}

type Query struct {
}
